[PARSER]
    Name        docker
    Format      json
    Time_Key    time
    Time_Format %Y-%m-%dT%H:%M:%S.%L
    Time_Keep   On

[PARSER]
    Name        nginx
    Format      json
    Time_Key    time_local
    Time_Format %d/%b/%Y:%H:%M:%S %z
    Time_Keep   On
    Types       status:integer request_time:float upstream_response_time:float bytes_sent:integer
